version: '3.4'

services:
  nodemongodbdocker:
    container_name: node_mongo_app_example
    image: nodemongodbdocker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:3000
    links: 
      - mongo
    volumes: 
      - .:/usr/src/app
  mongo:
    container_name: mongo_db
    image: mongo
    ports: 
      - 27017:27017
    logging: 
      driver: none
